# Build pipeline for publishing NPM (NodeJS) module to Azure Artifacts
# Stage 'publish' publishes the NPM module to Azure Artifacts
# Note: The current version is used as set in package.json is used. Make sure that you use a
#       version which is not yet used, other the stage will fail.
 
trigger:
- none
 
# Global variables for all stages
variables:
  vmImageNamePool: 'ubuntu-latest'
 
stages:
# Prepare
- stage: prepare
  displayName: Build and test artifacts
  jobs:
  - job: Build
    displayName: Build artifacts
    pool:
      vmImage: $(vmImageNamePool)
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
        displayName: 'Install Node.js v12'
 
      - script: |
          npm install
        displayName: 'Install NPM dependencies'
 
# Publish
- stage: publish
  displayName: Publish to Azure Artifacts
  jobs:
  - job: publish
    displayName: Publish NPM module
    pool:
      vmImage: $(vmImageNamePool)
    steps:
    - checkout: self
      persistCredentials: true
      clean: true